### PR TITLE
Replace Split to SplitN for contains colon value map

### PR DESCRIPTION
**Pull request by hori-ryota**
For map that has value with colon like url.

### CODE REVIEW

**Comment by sp-jordi-forns** [comment]
I'd love to have that one! Maybe you could add a test to make sure the feature doesn't break.

**Comment by casterx** [comment]
+1, we really need this!

**Comment by blopker** [comment]
Hey, I tracked and issue I'm having with Drone.io here. I think this PR would solve the issue! See here for context: https://discourse.drone.io/t/setting-global-agent-environment-url-variables/4516

**Comment by heilaaks** [comment]
A use case could be also defining a private Docker registry that is not running in the default HTTPS 443 port.  I have been trying to figure out a way how to share e.g. a common private registry configuration for repositories in order to avoid changing global CI configuration manually in repositories.

This would require something like: ``--env=DRONE_RUNNER_ENVIRON=CI_REGISTRY:10.164.132.33:444`` to start the Drone container.

+1 for a .env file to define this instead of a single environment variable that stacks all the variables.

**Comment by teepark** [comment]
Good fix, thanks @hori-ryota!

Before merging can we have a test?

**Comment by hori-ryota** [comment]
@sp-jordi-forns @teepark Sorry for delay, tests added

**Comment by vearutop** [comment]
What should be the env var value in case one of the items needs comma in own value? For example a DSN with password containing `,`?

**Comment by hori-ryota** [comment]
It's a good subject but not the scope of this lssue.

**Comment by sp-jordi-forns** [comment]
@vearutop Those should be URL-encoded IMHO.

**Comment by TonyPythoneer** [comment]
Hi @teepark 
Could you review it?

**Comment by kfreiman** [comment]
@teepark, is something blocking this pr?

**Comment by ashwilliams1** [comment]
bump, anything we can do to help get this merged? thanks!

**Comment by hori-ryota** [comment]
@teepark Could you review and merge this?

**Comment by maximbaz** [comment]
This is definitely a valuable PR, but it will not cover all cases, for example I need to create a map where URLs are the keys and not the values.

Something like #153 is more a complete fix, it also makes use of `SplitN`, but additionally allows to define a custom map separator. Then, you can say that for example `🦀` is the separator and only the first occurrence of it should split key from value.

**Comment by hori-ryota** [comment]
> This is definitely a valuable PR, but it will not cover all cases, 

That's right. However, at present, I think this PR is an appropriate size change.

**Comment by hori-ryota** [comment]
:eyes:

**Comment by clarktlaugh** [comment]
Is there an ETA on when this will be merged?

**Comment by hori-ryota** [comment]
@kelseyhightower @teepark hello?

**Comment by hori-ryota** [comment]
Give up on maintaining this repository. Close.

**Pull request closed without merging**
