### PR TITLE
Add support for encoding.BinaryUnmarshaler

### LINKED ISSUE #98: Add support for net.URL
I think that the net.URL is a very common type to be used in configuration.
I already found myself several times defining a URL configuration argument as a string type, and performing `url.Parse` to get a `*url.URL` object.
Since this type is not implementing the Setter or Decoder interface, it can't be used as is.
I think that adding a support to this type would be very useful.

### PR DESCRIPTION
**Pull request by hypnoglow**
Fixes #98 - `url.URL` implements `encoding.BinaryUnmarshaler` but not `encoding.TextUnmarshaler` ([note](https://github.com/golang/go/blob/master/src/net/url/url.go#L1061):thinking:)

### CODE REVIEW

**Comment by hypnoglow** [comment]
Ah, `url.URL` implements `encoding.BinaryUnmarshaler` [since 1.8](https://golang.org/doc/go1.8#net_url).

**Comment by hypnoglow** [comment]
Fixed tests for `url.URL` by adding a build tag.

**Comment by teepark** [comment]
Looks good, thanks @hypnoglow!

**Comment by ivanovaleksey** [comment]
Thanks for implementing this!
Maybe we could release a new version? It has been a long since v1.3.0.

**Pull request merged**
